# Generated by Django 3.1.7 on 2021-07-06 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea_app', '0002_auto_20210705_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='ciudad',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='codigo',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='arribos', to='aerolinea_app.aeropuerto'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='aerolinea_app.aeropuerto'),
        ),
    ]
