# Generated by Django 3.1.7 on 2021-07-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea_app', '0003_auto_20210705_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuerto',
            name='ciudad',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='aeropuerto',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
    ]
