# Generated by Django 3.1.7 on 2021-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea_app', '0005_auto_20210706_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('vuelos', models.ManyToManyField(blank=True, related_name='pasajeros', to='aerolinea_app.Vuelo')),
            ],
        ),
    ]
